### ISSUE TITLE
element hidding whitelists undesired behaviour

### ISSUE THREAD

**Issue by wmyrda** [essandess/adblock2privoxy#20]
To decrease element hiding directory quite substantialy I removed from filter lists all rules starting with `##` to rely only on rules dedicated for particular sites. It turned out each file still had over ~150 entries not related to the site. They came from element hidding exception rules
eg. `~tv.mail.ru##.js-springs__top` instead of only removing `.js-springs__top` for that particular site it also installed it for every other site (about 80 000 of them). While I undestard logic behind it I do not think it should be done if there is no `##.js-springs__top` to match entries for all sites.

**Comment by essandess** [comment]
I don’t see the as an issue.

That’s what this rule says: apply to all domains except the one(s) specified. You can’t put that rule in the global css rules because then it would apply globally.

The `css` directory is large, but it’s not that bad, and these rules are only loaded on a site-by-site basis, so Elena hiding is working as expected.
