### ISSUE TITLE
Add badfilter support

### ISSUE THREAD

**Issue by jayvdb** [essandess/adblock2privoxy#5]
Rules with `badfilter` should be used to eliminate bad rules.

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#badfilter

This is needed to use https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt

**Comment by essandess** [comment]
Just add url’s to the command line to incorporate additional rules:

```
adblock2privoxy -p /usr/local/etc/adblock2privoxy/privoxy -w /usr/local/etc/adblock2privoxy/css -d 10.0.1.3:8119 \
  https://easylist.to/easylist/easyprivacy.txt  \
  https://easylist.to/easylist/easylist.txt  \
  https://easylist.to/easylist/fanboy-annoyance.txt  \
  https://easylist.to/easylist/fanboy-social.txt  \
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt  \
  https://easylist-downloads.adblockplus.org/malwaredomains_full.txt  \
  https://raw.githubusercontent.com/Dawsey21/Lists/master/adblock-list.txt \
  https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
```

Note that in the parent repo [easylist-pac-privoxy](../../easylist-pac-privoxy), the default behavior uses a supervised classifier to downselect the number of rules to a few thousand so that the resulting `proxy.pac` JavaScript file works well on mobile devices. All rules are not by default included in `proxy.pac`, but `adblock2privoxy` does incorporate all rules.

I’ll look into adding this url as the default option in both repos.

**Comment by essandess** [comment]
Before I do that, what’s going on in this `easyprivacy` upstream [issue](https://github.com/coala/gci-leaders/issues/144)? Will `easyprivacy` incorporate `unbreak.txt` itself?

**Comment by essandess** [comment]
That’s still upstream. I can’t incorporate fixes into repos from other rule sets.

Thanks for pointing out the issue and the fix for anyone who wants to DIY.
